#!/bin/sh

THIS=$(basename $0)

source /usr/local/lib/utils
source /usr/local/lib/firmware_update

case "$1" in
    start)
	keys=$(devmem 0x01c20500 16)
	if [ "${keys}" != "0xF83F" ]; then

	    # Automatic firmware update requested
	    find_firmware_update /mnt
	    update_status=$?
	    if [ ${update_status} -eq 1 ]; then
		menu &
		exit 1
	    fi
	    if [ ${update_status} -eq 2 ]; then
		notif display 10 "      MULTIPLE UPDATE FILES^       KEEP ONLY ONE .FWU"
		menu &
		exit 1
	    fi
	    if ! install_firmware_update "${FIRMWARE_UPDATE_FILE}"; then
		notif display 10 "         CORRUPTED^        UPDATE FILE"
		menu &
		exit 1
	    fi
	    notif set 0 "^^^^^^^^         RESTARTING...^^^^^^^^"
	    normal_mode
	else

	    # Manual Recovery mode following Fn + Start keypress during boot
	    menu &
	fi
	;;
    stop)
	;;
    *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
