#!/bin/sh
#
# Start/stop dhcpcd
#

DAEMON=/sbin/dhcpcd
CONFIG=/etc/dhcpcd.conf
PIDFILE=/var/run/dhcpcd.pid
. /usr/local/lib/usb_network

[ -f $CONFIG ] || exit 0

case "$1" in
  start)
	usb_network_is_ready || exit 0
	echo -n "Starting dhcpcd: "
	start-stop-daemon -S -x "$DAEMON" -p "$PIDFILE" -o -- -f "$CONFIG" > /dev/null 2>&1
	daemon_status=$?
	if [ "$daemon_status" -eq 0 ]; then
	  echo "OK"
	else
	  echo "ERROR"
	fi
	exit "$daemon_status"
	;;
  stop)
	echo -n "Stopping dhcpcd: "
	start-stop-daemon -K -x "$DAEMON" -p "$PIDFILE" -o > /dev/null 2>&1
	daemon_status=$?
	if [ "$daemon_status" -eq 0 ]; then
	  echo "OK"
	else
	  echo "ERROR"
	fi
	exit "$daemon_status"
	;;
  reload|force-reload)
	echo -n "Reloading dhcpcd configuration: "
	"$DAEMON" -s reload >/dev/null 2>&1
	daemon_status=$?
	if [ "$daemon_status" -eq 0 ]; then
	  echo "OK"
	else
	  echo "ERROR"
	fi
	exit "$daemon_status"
	;;
  restart)
	"$0" stop
	sleep 1 # Prevent race condition: ensure dhcpcd stops before start.
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}"
	exit 1
esac
