FROM localhost/funkey-os-build:focal
RUN apt-get update \
 && apt-get install -y -q --no-install-recommends curl dash fonts-dejavu-core libsdl1.2-dev libsdl-ttf2.0-dev \
 && rm -rf /var/lib/apt/lists/*
ENV RUSTUP_HOME=/opt/rustup CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal --default-toolchain 1.91.0 --target arm-unknown-linux-musleabihf \
 && rustc --version && cargo --version && chmod -R a+rwX /opt/cargo /opt/rustup
