#!/bin/sh

# Uncomment the following line to get debug info
#set -x

. /usr/local/lib/usb_network

if usb_data_is_configured; then
    # The gadget was enumerated by a data host, not merely powered.
    echo "yes"
    exit 0
fi

echo "no"
exit 1
