#!/bin/sh

SELF=${SELF:-$(basename "$0")}

source /usr/local/lib/utils

GADGET=/sys/kernel/config/usb_gadget/FunKey

test -r /etc/default/usb-gadget && source /etc/default/usb-gadget
USB_NETWORK=${USB_NETWORK:-auto}
USB_MASS_STORAGE=${USB_MASS_STORAGE:-1}
USB_NETWORK_DRIVER=${USB_NETWORK_DRIVER:-auto}

case "$USB_NETWORK" in
    always) USBNET=1 ;;
    never) USBNET=0 ;;
    *) [ ! -f /mnt/usbnet ]; USBNET=$? ;;
esac

case "$USB_NETWORK_DRIVER" in
    rndis|ecm|ncm) NETWORK_KIND=$USB_NETWORK_DRIVER ;;
    *)
        if [ -f /mnt/usbnet-ncm ]; then
            NETWORK_KIND=ncm
        elif [ -f /mnt/usbnet-ecm ]; then
            NETWORK_KIND=ecm
        else
            NETWORK_KIND=rndis
        fi
        ;;
esac
NETWORK_FUNCTION=$NETWORK_KIND.usb0

[ ! -f /mnt/adb ]
ADB=$?

ID_VENDOR=0x1d6b
ID_PRODUCT=0x0104

SERIAL="$(grep Serial /proc/cpuinfo | sed 's/Serial\s*: \(\w*\)/\1/')"
MAC="$(echo "$SERIAL" | sed 's/\(\w\w\)/:\1/g' | cut -b 2-)"
MAC_HOST="12$(echo "$MAC" | cut -b 3-)"
MAC_DEV="02$(echo "$MAC" | cut -b 3-)"

init_usb_gadget()
{
    if [ -e "$GADGET" ]; then
        return 0
    fi

    if [ "$ADB" -eq 1 ]; then
        adb start
        return 0
    fi

    modprobe -r g_ether 2>/dev/null || true
    modprobe -r g_ncm 2>/dev/null || true
    modprobe -r g_mass_storage 2>/dev/null || true
    modprobe libcomposite

    if [ "$USBNET" -eq 1 ]; then
        case "$NETWORK_KIND" in
            rndis) modprobe usb_f_rndis ;;
            ecm) modprobe usb_f_ecm ;;
            ncm) modprobe usb_f_ncm ;;
        esac
    fi

    local udc_driver
    udc_driver=$(ls /sys/class/udc | cut -f1 | head -n 1)
    [ -n "$udc_driver" ] || die 20 "no USB device controller is available"

    mkdir "$GADGET"
    mkdir "$GADGET/strings/0x409"
    mkdir "$GADGET/configs/FunKey.1"
    mkdir "$GADGET/configs/FunKey.1/strings/0x409"
    test "$USBNET" -eq 1 && mkdir "$GADGET/functions/$NETWORK_FUNCTION"
    test "$USB_MASS_STORAGE" -eq 1 &&
        mkdir "$GADGET/functions/mass_storage.mmcblk0p4"

    echo 0x0200 > "$GADGET/bcdUSB"

    if [ "$USBNET" -eq 1 ]; then
        echo 0x02 > "$GADGET/bDeviceClass"
        echo 0x00 > "$GADGET/bDeviceSubClass"
    fi

    echo "$ID_VENDOR" > "$GADGET/idVendor"
    echo "$ID_PRODUCT" > "$GADGET/idProduct"
    echo 0x0100 > "$GADGET/bcdDevice"

    echo FunKey > "$GADGET/strings/0x409/manufacturer"
    echo "RG Nano Iroh" > "$GADGET/strings/0x409/product"
    echo "$SERIAL" > "$GADGET/strings/0x409/serialnumber"

    if [ "$USBNET" -eq 1 ] && [ "$NETWORK_KIND" = rndis ]; then
        echo 1 > "$GADGET/os_desc/use"
        echo 0xcd > "$GADGET/os_desc/b_vendor_code"
        echo MSFT100 > "$GADGET/os_desc/qw_sign"
    fi

    echo 500 > "$GADGET/configs/FunKey.1/MaxPower"

    if [ "$USBNET" -eq 1 ] && [ "$USB_MASS_STORAGE" -eq 1 ]; then
        echo "Mass Storage + $(echo "$NETWORK_KIND" | tr 'a-z' 'A-Z')" \
            > "$GADGET/configs/FunKey.1/strings/0x409/configuration"
    elif [ "$USBNET" -eq 1 ]; then
        echo "$(echo "$NETWORK_KIND" | tr 'a-z' 'A-Z') Network" \
            > "$GADGET/configs/FunKey.1/strings/0x409/configuration"
    else
        echo "Mass Storage" \
            > "$GADGET/configs/FunKey.1/strings/0x409/configuration"
    fi

    if [ "$USBNET" -eq 1 ]; then
        echo "$MAC_HOST" > "$GADGET/functions/$NETWORK_FUNCTION/host_addr"
        echo "$MAC_DEV" > "$GADGET/functions/$NETWORK_FUNCTION/dev_addr"

        if [ "$NETWORK_KIND" = rndis ]; then
            ln -s "$GADGET/configs/FunKey.1" "$GADGET/os_desc"
            echo RNDIS \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/compatible_id"
            echo 5162001 \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id"

            mkdir "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Icons"
            echo 2 \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Icons/type"
            echo "%SystemRoot%\\system32\\shell32.dll,-233" \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Icons/data"

            mkdir "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Label"
            echo 1 \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Label/type"
            echo "RG Nano Device" \
                > "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Label/data"
        fi
    fi

    if [ "$USB_MASS_STORAGE" -eq 1 ]; then
        echo 0 > "$GADGET/functions/mass_storage.mmcblk0p4/stall"
        echo 0 > "$GADGET/functions/mass_storage.mmcblk0p4/lun.0/cdrom"
        echo 0 > "$GADGET/functions/mass_storage.mmcblk0p4/lun.0/nofua"
        echo 1 > "$GADGET/functions/mass_storage.mmcblk0p4/lun.0/removable"
        echo "RG Nano Shared Disk" \
            > "$GADGET/functions/mass_storage.mmcblk0p4/lun.0/inquiry_string"
    fi

    if [ "$USBNET" -eq 1 ]; then
        ln -s "$GADGET/functions/$NETWORK_FUNCTION" \
            "$GADGET/configs/FunKey.1"

        # Bind once before mass storage is attached so usb0 exists before the
        # later network and Dropbear init scripts run.
        echo "$udc_driver" > "$GADGET/UDC"
        sleep 5
        echo > "$GADGET/UDC"
    fi

    if [ "$USB_MASS_STORAGE" -eq 1 ]; then
        ln -s "$GADGET/functions/mass_storage.mmcblk0p4" \
            "$GADGET/configs/FunKey.1"
    fi

    echo 0x00 > "$GADGET/bDeviceClass"
    echo "$udc_driver" > "$GADGET/UDC"
    return 0
}

deinit_usb_gadget()
{
    [ -e "$GADGET" ] || return 0

    echo > "$GADGET/UDC"

    test "$USB_MASS_STORAGE" -eq 0 ||
        rm -f "$GADGET/configs/FunKey.1/mass_storage.mmcblk0p4"
    if [ "$USBNET" -eq 1 ]; then
        rm -f "$GADGET/configs/FunKey.1/$NETWORK_FUNCTION"
    fi

    rmdir "$GADGET/configs/FunKey.1/strings/0x409"

    if [ "$USBNET" -eq 1 ] && [ "$NETWORK_KIND" = rndis ]; then
        rm -f "$GADGET/os_desc/FunKey.1"
    fi

    rmdir "$GADGET/configs/FunKey.1"

    if [ "$USBNET" -eq 1 ] && [ "$NETWORK_KIND" = rndis ]; then
        rmdir "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Icons"
        rmdir "$GADGET/functions/rndis.usb0/os_desc/interface.rndis/Label"
    fi

    test "$USB_MASS_STORAGE" -eq 0 ||
        rmdir "$GADGET/functions/mass_storage.mmcblk0p4"
    if [ "$USBNET" -eq 1 ]; then
        rmdir "$GADGET/functions/$NETWORK_FUNCTION"
    fi

    rmdir "$GADGET/strings/0x409"
    rmdir "$GADGET"

    modprobe -r usb_f_mass_storage usb_f_rndis usb_f_ecm usb_f_ncm 2>/dev/null ||
        true
}
